export * from './DashboardPage';
export * from './HomePage';
export * from './LoginPage';
export * from './RegisterPage';
export * from './PrivatePage1'
export * from './PrivatePage2'
export * from './PrivatePage3'
export * from './PublicPage1'
export * from './PublicPage2'
export * from './PublicPage3'